## Fun play with Graph Convolutional Network

https://towardsdatascience.com/how-to-do-deep-learning-on-graphs-with-graph-convolutional-networks-7d2250723780?_branch_match_id=583671151297928547

In [1]:
import numpy as np

In [2]:
# numpy adjacency matrix representation

A = np.matrix([
    [0, 1, 0, 0],
    [0, 0, 1, 1],
    [0, 1, 0, 0],
    [1, 0, 1, 0]],
    dtype = float
)

In [6]:
A

matrix([[0., 1., 0., 0.],
        [0., 0., 1., 1.],
        [0., 1., 0., 0.],
        [1., 0., 1., 0.]])

In [3]:
# features
X = np.matrix([
    [i, -i]
    for i in range(A.shape[0])
    ], dtype=float)

In [4]:
X

matrix([[ 0.,  0.],
        [ 1., -1.],
        [ 2., -2.],
        [ 3., -3.]])

In [5]:
# Propagation Rule

A * X

matrix([[ 1., -1.],
        [ 5., -5.],
        [ 1., -1.],
        [ 2., -2.]])

The representation of each node (each row) is now a sum of its neighbors features! 

In [7]:
# Adding Self-Loops

I = np.matrix(np.eye(A.shape[0]))
I

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [8]:
A_hat = A + I
A_hat

matrix([[1., 1., 0., 0.],
        [0., 1., 1., 1.],
        [0., 1., 1., 0.],
        [1., 0., 1., 1.]])

In [9]:
A_hat * X

matrix([[ 1., -1.],
        [ 6., -6.],
        [ 3., -3.],
        [ 5., -5.]])

In [13]:
a = np.array([0, 1, 2, 3])
b = np.array([1, 2, 3, 4])

In [14]:
a * b

array([ 0,  2,  6, 12])